### ISSUE TITLE
My Appointment Book From the  hspointofsalepro repository

### ISSUE THREAD

**Issue by Tom01810** [Tom01810/Testings-and-Features#1]
Here is the first version and I will update it asap. 
Please report all the issues in the hspointofsalepro repository with pictures or videos.

[My Appointment Book Ver. 1.01.pdf](https://github.com/Tom01810/Testings-and-Features/files/218276/My.Appointment.Book.Ver.1.01.pdf)

**Comment by Tom01810** [comment]
I have updated the file.
https://github.com/Tom01810/Testings-and-Features/files/218276/My.Appointment.Book.Ver.1.01.pdf

**Comment by tmaximecarlos** [comment]
thank you

**Comment by Tom01810** [comment]
You go to the hspointofsalepro repository to report any issue you may encounter,
