### ISSUE TITLE
Style add address

### ISSUE THREAD

**Issue by astrid2002** [Tom01810/Testings-and-Features#8]
The dropdown for  for the country in add address for a customer  does not display correctly
![screen shot 2016-06-09 at 9 00 36 pm](https://cloud.githubusercontent.com/assets/13542427/15938679/466d7536-2e85-11e6-8589-a6e58b189848.png)

**Comment by Tom01810** [comment]
@astrid2002 

Please report the issues in the appropriate repository

https://github.com/Tom01810/hspointofsalepro

https://github.com/Tom01810/jmarketplace

https://github.com/Tom01810/iziposproductsslide
